# from GitHub, overriding the name and specifying a specific tag
#- src: https://github.com/lcacciagioni/supervisord
#  version: master
#  name: supervisord

# gitinsky
## It is required for ansible-role-redmine

- src: https://github.com/gitinsky/ansible-role-ruby-rvm.git
  name: ruby-rvm
