---
- name: generate passenger.conf
  shell: "su redmine -c 'source {{ rvm_path }} && passenger-install-apache2-module --snippet' > /etc/apache2/conf.d/passenger.conf"
  args:
    chdir: "{{ redmine_path }}/current"
  notify: reload apache
  tags: debug
