production:
   email_delivery:
     delivery_method: :smtp
     smtp_settings:
       address: "localhost"
       enable_starttls_auto: false
       domain: {{ redmine_email_domain }}
       port: 25
